SEED = 1
VERBOSITY = 2

X_PATHS = ["sample/QM7/QM7_overlap.npy",]
X_NAMES = ["5-component overlap"]
X_NORMS = ["standard"]

Y_PATH = "sample/QM7/atomization_energy.npy"
Y_NAME = "atomization energy"
Y_NORM = "standard"

USE_PREDEFINED_SPLITS = False
PREDEF_TRAINING_IDX_PATH = "predef_training_idx.npy"
PREDEF_VAL_KFOLD_IDX_PATH = "predef_val_kfold_idx.npy"
PREDEF_TESTING_IDX_PATH  = "predef_testing_idx.npy"

N_SAMPLES = 7165
TRAIN_VAL_SPLIT = 0.70
N_KFOLD = 5
STRATIFY = True
N_STRATA = 5

KRR_KERNEL = "rbf"
KRR_ALPHA_BOUNDS = (1e-8, 1e2)
KRR_GAMMA_BOUNDS = (1e-6, 1e2)
KRR_RANDOM_SEARCH_STAGE1 = 25
KRR_RANDOM_SEARCH_STAGE2 = 25
KRR_RANDOM_SEARCH_STAGE3 = 25

# None follows sklearn's default; -1 uses all available cores.
KRR_RANDOM_SEARCH_N_JOBS = -1
KRR_COMPUTE_DTYPE = "float32"
KRR_USE_DISTANCE_CACHE = True
KRR_DISTANCE_BLOCK_SIZE = 1024
KRR_DISTANCE_CACHE_DTYPE = KRR_COMPUTE_DTYPE
KRR_DISTANCE_CACHE_N_JOBS = -1
KRR_DISTANCE_CACHE_MEMORY_FRACTION = 0.80
KRR_RANDOM_SEARCH_PLOT_PATH = "random_search_validation_error.png"
KRR_BAYESIAN_SEARCH_TRIALS = 50
KRR_BAYESIAN_SEARCH_TIMEOUT = None
KRR_BAYESIAN_SEARCH_PATIENCE = 25
KRR_SCORE_METRIC = "neg_mean_absolute_error"
