import scipy.io as io
import numpy as np
from pathlib import Path


# =========================
# User settings
# =========================

QM7B_MAT_PATH = "sample/QM7b/qm7b.mat"

# Generated by the matching script
GOOD_MAT_INDICES_PATH = "sample/QM7b/qm7b_good_mat_indices.npy"
GOOD_XYZ_INDICES_PATH = "sample/QM7b/qm7b_good_xyz_indices.npy"

# Output directory
OUT_DIR = Path("sample/QM7b/aligned_targets")
OUT_DIR.mkdir(parents=True, exist_ok=True)

SAVE_ALL_TARGETS = True
SAVE_INDIVIDUAL_TARGETS = True


# =========================
# Target names
# =========================

target_names = [
    "ae_pbe0",
    "zindo_excitation_energy_with_the_most_absorption",
    "zindo_highest_absorption",
    "zindo_homo",
    "zindo_lumo",
    "zindo_1st_excitation_energy",
    "zindo_ionization_potential",
    "zindo_electron_affinity",
    "ks_homo",
    "ks_lumo",
    "gw_homo",
    "gw_lumo",
    "polarizability_pbe",
    "polarizability_scs",
]


# =========================
# Load original QM7b targets
# =========================

qm7b = io.loadmat(QM7B_MAT_PATH)

if "T" not in qm7b:
    raise KeyError(f"Could not find key 'T' in {QM7B_MAT_PATH}")

T = np.asarray(qm7b["T"], dtype=float)

for i in range(np.shape(T)[1]):
    print(f"{target_names[i]} {np.mean(T[i]):.04f} {np.mean(np.abs(T[i])):.04f} {np.sqrt(np.mean(T[i]**2)):.04f}")

# # Handle possible transposed layout
# if T.shape == (14, 7211):
#     T = T.T

# if T.shape[1] != len(target_names):
#     raise ValueError(
#         f"Expected {len(target_names)} target columns, but got T.shape={T.shape}"
#     )

# print("Loaded original QM7b targets")
# print("----------------------------")
# print(f"T shape: {T.shape}")


# # =========================
# # Load matching indices
# # =========================

# good_mat_indices = np.load(GOOD_MAT_INDICES_PATH)
# good_xyz_indices = np.load(GOOD_XYZ_INDICES_PATH)

# good_mat_indices = np.asarray(good_mat_indices, dtype=int)
# good_xyz_indices = np.asarray(good_xyz_indices, dtype=int)

# if good_mat_indices.ndim != 1:
#     raise ValueError(f"good_mat_indices must be 1D, got shape {good_mat_indices.shape}")

# if good_xyz_indices.ndim != 1:
#     raise ValueError(f"good_xyz_indices must be 1D, got shape {good_xyz_indices.shape}")

# if len(good_mat_indices) != len(good_xyz_indices):
#     raise ValueError(
#         f"good_mat_indices and good_xyz_indices length mismatch: "
#         f"{len(good_mat_indices)} vs {len(good_xyz_indices)}"
#     )

# print()
# print("Loaded matching indices")
# print("-----------------------")
# print(f"good_mat_indices shape: {good_mat_indices.shape}")
# print(f"good_xyz_indices shape: {good_xyz_indices.shape}")


# # =========================
# # Reorder targets
# # =========================

# # This is the key operation:
# #
# #   descriptors computed from QM7b.xyz at row good_xyz_indices[k]
# #   correspond to
# #   target row T_good_xyz_order[k]
# #
# T_good_xyz_order = T[good_mat_indices]

# print()
# print("Generated aligned target matrix")
# print("-------------------------------")
# print(f"T_good_xyz_order shape: {T_good_xyz_order.shape}")


# # =========================
# # Save outputs
# # =========================

# if SAVE_ALL_TARGETS:
#     np.save(OUT_DIR / "qm7b_T_good_xyz_order.npy", T_good_xyz_order)
#     np.save(OUT_DIR / "qm7b_good_xyz_indices.npy", good_xyz_indices)
#     np.save(OUT_DIR / "qm7b_good_mat_indices.npy", good_mat_indices)

#     with open(OUT_DIR / "target_names.txt", "w") as f:
#         for i, name in enumerate(target_names):
#             f.write(f"{i},{name}\n")

# if SAVE_INDIVIDUAL_TARGETS:
#     for col, name in enumerate(target_names):
#         y = T_good_xyz_order[:, col]
#         np.save(OUT_DIR / f"QM7b_good_{name}.npy", y)

# print()
# print("Saved aligned targets")
# print("---------------------")
# print(f"Output directory: {OUT_DIR}")
# print(f"All targets:      {OUT_DIR / 'qm7b_T_good_xyz_order.npy'}")
# print(f"Good XYZ indices: {OUT_DIR / 'qm7b_good_xyz_indices.npy'}")
# print(f"Target names:     {OUT_DIR / 'target_names.txt'}")


# # =========================
# # Example usage reminder
# # =========================

# print()
# print("Usage with descriptors computed in raw QM7b.xyz order")
# print("-----------------------------------------------------")
# print("X_desc = np.load('your_qm7b_descriptors.npy')")
# print(f"good_idx = np.load('{OUT_DIR / 'qm7b_good_xyz_indices.npy'}')")
# print(f"T_good = np.load('{OUT_DIR / 'qm7b_T_good_xyz_order.npy'}')")
# print("X_good = X_desc[good_idx]")
# print("y_ae_pbe0 = T_good[:, 0]")
